# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jin/jin/github/shell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jin/jin/github/shell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jin/jin/github/shell/CMakeFiles /home/jin/jin/github/shell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jin/jin/github/shell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shell.out

# Build rule for target.
shell.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shell.out
.PHONY : shell.out

# fast build rule for target.
shell.out/fast:
	$(MAKE) -f CMakeFiles/shell.out.dir/build.make CMakeFiles/shell.out.dir/build
.PHONY : shell.out/fast

cmd.o: cmd.c.o

.PHONY : cmd.o

# target to build an object file
cmd.c.o:
	$(MAKE) -f CMakeFiles/shell.out.dir/build.make CMakeFiles/shell.out.dir/cmd.c.o
.PHONY : cmd.c.o

cmd.i: cmd.c.i

.PHONY : cmd.i

# target to preprocess a source file
cmd.c.i:
	$(MAKE) -f CMakeFiles/shell.out.dir/build.make CMakeFiles/shell.out.dir/cmd.c.i
.PHONY : cmd.c.i

cmd.s: cmd.c.s

.PHONY : cmd.s

# target to generate assembly for a file
cmd.c.s:
	$(MAKE) -f CMakeFiles/shell.out.dir/build.make CMakeFiles/shell.out.dir/cmd.c.s
.PHONY : cmd.c.s

shell.o: shell.c.o

.PHONY : shell.o

# target to build an object file
shell.c.o:
	$(MAKE) -f CMakeFiles/shell.out.dir/build.make CMakeFiles/shell.out.dir/shell.c.o
.PHONY : shell.c.o

shell.i: shell.c.i

.PHONY : shell.i

# target to preprocess a source file
shell.c.i:
	$(MAKE) -f CMakeFiles/shell.out.dir/build.make CMakeFiles/shell.out.dir/shell.c.i
.PHONY : shell.c.i

shell.s: shell.c.s

.PHONY : shell.s

# target to generate assembly for a file
shell.c.s:
	$(MAKE) -f CMakeFiles/shell.out.dir/build.make CMakeFiles/shell.out.dir/shell.c.s
.PHONY : shell.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... shell.out"
	@echo "... edit_cache"
	@echo "... cmd.o"
	@echo "... cmd.i"
	@echo "... cmd.s"
	@echo "... shell.o"
	@echo "... shell.i"
	@echo "... shell.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

